### ISSUE TITLE
hg pull fails

### ISSUE THREAD

**Issue by memecode** [memecode/phabricator#1]
hg: v6.1.1
Apache: v2.4.41
php: 7.4.29

"hg pull -u" fails with the following error:
`abort: HTTP Error 500: Error 1: ** unknown exception encountered, please report by visiting`

Phabricator is calling 'hg' with the following args:
`/usr/bin/sudo -E -n -u daemon -- /usr/local/bin/hg -R /var/www/hg/43/ serve --stdio`

Stdio passed:
`listkeys\n`

Phabricator stack:
```
[0]=/var/www/phab/phabricator/src/applications/diffusion/controller/DiffusionServeController.php:488 - serveMercurialRequest
[1]=/var/www/phab/phabricator/src/applications/diffusion/controller/DiffusionServeController.php:402 - serveVCSRequest
[2]=/var/www/phab/phabricator/src/applications/diffusion/controller/DiffusionServeController.php:99 - serveRequest
[3]=/var/www/phab/phabricator/src/aphront/AphrontController.php:71 - handleRequest
[4]=/var/www/phab/phabricator/src/applications/diffusion/controller/DiffusionController.php:27 - delegateToController
[5]=/var/www/phab/phabricator/src/aphront/configuration/AphrontApplicationConfiguration.php:272 - willBeginExecution
[6]=/var/www/phab/phabricator/src/aphront/configuration/AphrontApplicationConfiguration.php:204 - processRequest
[7]=/var/www/phab/phabricator/webroot/index.php:38 - runHTTPRequest
```

Hg error:
```
Traceback (most recent call last):
  File "/usr/bin/hg", line 59, in <module>
    dispatch.run()
  File "/usr/local/lib/python3.8/dist-packages/mercurial/dispatch.py", line 143, in run
    status = dispatch(req)
  File "/usr/local/lib/python3.8/dist-packages/mercurial/dispatch.py", line 232, in dispatch
    status = _rundispatch(req)
  File "/usr/local/lib/python3.8/dist-packages/mercurial/dispatch.py", line 276, in _rundispatch
    ret = _runcatch(req) or 0
  File "/usr/local/lib/python3.8/dist-packages/mercurial/dispatch.py", line 452, in _runcatch
    return _callcatch(ui, _runcatchfunc)
  File "/usr/local/lib/python3.8/dist-packages/mercurial/dispatch.py", line 462, in _callcatch
    return scmutil.callcatch(ui, func)
  File "/usr/local/lib/python3.8/dist-packages/mercurial/scmutil.py", line 152, in callcatch
    return func()
  File "/usr/local/lib/python3.8/dist-packages/mercurial/dispatch.py", line 442, in _runcatchfunc
    return _dispatch(req)
  File "/usr/local/lib/python3.8/dist-packages/mercurial/dispatch.py", line 1255, in _dispatch
    return runcommand(
  File "/usr/local/lib/python3.8/dist-packages/mercurial/dispatch.py", line 900, in runcommand
    ret = _runcommand(ui, options, cmd, d)
  File "/usr/local/lib/python3.8/dist-packages/mercurial/dispatch.py", line 1267, in _runcommand
    return cmdfunc()
  File "/usr/local/lib/python3.8/dist-packages/mercurial/dispatch.py", line 1253, in <lambda>
    d = lambda: util.checksignature(func)(ui, *args, **strcmdopt)
  File "/usr/local/lib/python3.8/dist-packages/mercurial/util.py", line 1885, in check
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mercurial/commands.py", line 6588, in serve
    s.serve_forever()
  File "/usr/local/lib/python3.8/dist-packages/mercurial/wireprotoserver.py", line 539, in serve_forever
    self.serveuntil(threading.Event())
  File "/usr/local/lib/python3.8/dist-packages/mercurial/wireprotoserver.py", line 544, in serveuntil
    _runsshserver(self._ui, self._repo, self._fin, self._fout, ev)
  File "/usr/local/lib/python3.8/dist-packages/mercurial/wireprotoserver.py", line 489, in _runsshserver
    rsp = wireprotov1server.dispatch(repo, proto, request)
  File "/usr/local/lib/python3.8/dist-packages/mercurial/wireprotov1server.py", line 78, in dispatch
    args = proto.getargs(spec)
  File "/usr/local/lib/python3.8/dist-packages/mercurial/wireprotoserver.py", line 395, in getargs
    arg, l = argline.split()
ValueError: not enough values to unpack (expected 2, got 0)
```

So obviously there is some arguments not being passed into hg via the stdin that should be there.

**Comment by memecode** [comment]
Fix:

In phabricator/src/applications/diffusion/controller/DiffusionServeController.php

There is a function private function getMercurialArguments() that provides arguments to serveMercurialRequest. Currently it's looking for HTTP_X_HGARG_## parameters in the _SERVER variable. For whatever reason those don't exist with my setup. But the arguments ARE visible in $_SERVER["QUERY_STRING"]. By passed that to PhutilQueryStringParser it fixes the problem.
